//
//  Constants.swift
//  teste-qranio-thomas
//
//  Created by Thomás Marques Brandão Reis on 01/03/19.
//  Copyright © 2019 Thomás Marques Brandão Reis. All rights reserved.
//

import Foundation

struct Constants {
    
    static let API_KEY_NASA = "vAZJdvWRJvwJJKFTtWs8t1HHiaXrc6hantKQuxNI"
    static let PRIV_KEY_MARVEL = "f28dd34363c41e5c35036edb4fae4a414c5fcc82"
    static let PUB_KEY_MARVEL = "e2ba7dcbf15d280e107821f36c762dc6"
    
    static let START_DATE = "2019-02-27"
    static let END_DATE = "2019-03-03"
    
    static let UID = "uid"
    static let ERROR = "Error"
    static let OK = "Ok"
    static let USERS = "users"
    static let NAME = "name"
    static let EMAIL = "email"
    static let CITY = "city"
    static let SUCCESS = "Success"
    static let USER_SUCCESSFULLY_REGISTERED = "User successfully registered."
    static let YES = "Yes"
    static let NO = "No"
    static let WARNING = "Warning"
    static let MESSAGE_LOGOUT = "Are you sure you want to quit?"
    static let ID = "id"
    static let ABSOLUTE_MAGNITUDE_LABEL = "ab"
    static let ABSOLUTE_MAGNITUDE_H = "absolute_magnitude_h"
    static let IS_POTENTIALLY_HAZARDOUS_ASTEROID = "is_potentially_hazardous_asteroid"
    static let IS_SENTRY_OBJECT = "is_sentry_object"
    static let NAME_LIMITED = "name_limited"
    static let DESIGNATION = "designation"
    static let NASA_JAPA_URL = "nasa_jpl_url"
    static let ESTIMATED_DIAMETER = "estimated_diameter"
    static let ORBITAL_DATA = "orbital_data"
    static let SENTRY_DATA = "sentry_data"
    static let ORBIT_DETERMINATION_DATE = "orbit_determination_date"
    static let FIRST_OBSERVATION_DATE = "first_observation_date"
    static let LAST_OBSERVATION_DATE = "last_observation_date"
    static let DATA_ARC_IN_DAYS = "data_arc_in_days"
    static let OBESERVATIONS_USED = "observations_used"
    static let ORBIT_UNCERTAINTY = "orbit_uncertainty"
    static let MINIMUM_ORBIT_INTERSECTION = "minimum_orbit_intersection"
    static let JUPITER_TISSERAND_INVARIANT = "jupiter_tisserand_invariant"
    static let EPOCH_OSCULATION = "epoch_osculation"
    static let ECCENTRICITY = "eccentricity"
    static let SEMI_MAJOR_AXIS = "semi_major_axis"
    static let INCLINATION = "inclination"
    static let ASCENDING_NODE_LONGITUDE = "ascending_node_longitude"
    static let ORBITAL_PERIOD = "orbital_period"
    static let PERIHELION_DISTANCE = "perihelion_distance"
    static let PERIHELION_ARGUMENT = "perihelion_argument"
    static let APHELION_DISTANCE = "aphelion_distance"
    static let PERIHELION = "perihelion_time"
    static let MEAN_ANOMALY = "mean_anomaly"
    static let MEAN_MOTION = "mean_motion"
    static let EQUINOX = "equinox"
    static let NEAR_EARTH_OBJECT_COUNT = "near_earth_object_count"
    static let CLOSE_APPROACH_COUNT = "close_approach_count"
    static let LAST_UPDATED = "last_updated"
    static let SOURCE = "source"
    static let DESCRIPTION = "description"
    static let MODIFIED = "modified"
    static let RESOURCE_URI = "resourceURI"
    static let THUMBNAIL = "thumbnail"
    static let PATH = "path"
    static let COMICS = "comics"
    static let CANCEL = "Cancel"
    static let TITLE = "title"
    static let DATA = "data"
    static let RESULTS = "results"
    static let EVENTS = "events"
    static let COUNT_OBJECTS_CLOSE_IS = "Count of objects close to the ground is"
    static let CLOSE_APPROACH_COUNT_IS = "Close approach count is"
    static let LATEST_UPDATE_IS = "Latest update is"
    static let NEAR_EARTH_OBJECTS = "near_earth_objects"
    static let EMPTY_LIST_USERS = "No users available"
    static let EMPTY_LIST_ASTEROIDS = "No asteroid available"
    static let EMPTY_LIST_EVENTS = "No events available"
    static let EMPTY_LIST_COMICS = "No comics available"
    static let EMPTY_LIST_CHARACTERS = "No characters available"
    static let ERROR_LOADING_INFO = "Error loading info"
    static let LOADING = "Loading..."
    
}
